# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Javascript CI

on: [push, pull_request]

jobs:
  test:
    name: CI tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn package manger (which we use instead of npm)
        run: npm install -g yarn

      - name: Install npm dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
